version: 2

defaults: &defaults
  docker:
    - image: ncodamusic/linux-bundles:26
  working_directory: /root/workdir

jobs:
  clone_repos:
    <<: *defaults
    steps:
      - checkout

      - run:
          name: Make the Circle CI cache key
          command: make circle-cache-key

      - restore_cache:
          keys:
            - v1-repo-{{ checksum "FUJIAN_RELEASE" }}
            - v1-repo-{{ checksum "JULIUS_RELEASE" }}
            - v1-repo-{{ checksum "LYCHEE_RELEASE" }}
            - v1-pypi-{{ checksum "circle-cache-key" }}
            - v1-npm-{{ checksum "circle-cache-key" }}
      - run:
          name: Clone the repositories
          command: make clone-repos
      - save_cache:
          paths:
            - "/root/workdir/repos/fujian"
          key: v1-repo-{{ checksum "FUJIAN_RELEASE" }}
          when: on_success
      - save_cache:
          paths:
            - "/root/workdir/repos/julius"
          key: v1-repo-{{ checksum "JULIUS_RELEASE" }}
          when: on_success
      - save_cache:
          paths:
            - "/root/workdir/repos/lychee"
          key: v1-repo-{{ checksum "LYCHEE_RELEASE" }}
          when: on_success

      - persist_to_workspace:
          root: /root/workdir
          paths:
            - circle-cache-key
            - repos

  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /root/workdir

      - run:
          name: Install Python dependencies
          command: make build-venv
      - save_cache:
          paths:
            - "/root/.cache/pip"
          key: v1-pypi-{{ checksum "circle-cache-key" }}
          when: on_success


      - run:
          name: Install JavaScript dependencies
          command: make install-julius
      - save_cache:
          paths:
            - "/usr/local/share/.cache/yarn/v1"
            - "/root/.electron"
          key: v1-npm-{{ checksum "circle-cache-key" }}
          when: on_success


      - run:
          name: Do the whole build
          command: |
            make finish-ncoda
            make build-pex
            make build-julius
            make archive-http
            make archive-electron


      - store_artifacts:
          path: /root/workdir/ncoda-electron.xz
      - store_artifacts:
          path: /root/workdir/ncoda-http.xz

workflows:
  version: 2
  build-release:
    jobs:
      - clone_repos
      - build
          requires:
            - clone_repos
